----------------------- CUSTOMER BEHAVIOR ANALYSIS -----------------------------
select * from customer limit 10;

/* [Revenue] = (total amount of money a business, organization, or government receives or earns 
before any expenses are deducted Or sales*/

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) AS revenue
from customer
group by gender;
/* O/P- [male- 157890] & [female- 75191] so business often want to see this revenue split by gender 
bcz this will help them design better targeted campaigns for each group*/
-------------------------------------------------------------------------------------------------------------


--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);
-------------------------------------------------------------------------------------------------------------

--Q3. Which are the top 5 products with the highest average review rating? (IMP)
/* we have to calculate avg review rating for each product and then find out the top 5 products
with highest avg review rating*/
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "average_product_rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
/* O/P- we can see that gloves,sandles,boots,hat,skirt have the highest average product rating & 
products with consistently high ratings can be highlighted in marketing campaigns. They can also 
be sold at a premium price, that's why this Q is imp */
-------------------------------------------------------------------------------------------------------------


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
/* If we find out that express shipping customers spend more, then that's clear sign the business
should invest more in faster delivery options*/
select shipping_type, ROUND(AVG(purchase_amount),2) --we dont need to type caste it--
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;
/* O/P- so we can see that avg purchase amt is higher for express shipping rather than standard shipping, 
so as we had discussed shipping and other faster delivery options*/
-------------------------------------------------------------------------------------------------------------


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers?
/*so this is very common business Q, bcz subscriptions are a big driver of revenue. we are checking avg 
purchase amt & total revenue bet subscibers & non-subscribers, The results will tell us whether the subscription
program is working or not */
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend asc;
/* O/P- ok so now we know that 2847 customers are not subscribe yet, their avg spend is very similar to 
the people who have subscribed, but total revenue is very much higher than the people who have subscribed*/
-------------------------------------------------------------------------------------------------------------


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
/* so instead of just looking at total discount, here we have to  calculate the discount rate per product.
means, which products rely heavily on discounts to sell*/
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
-- so what am doing is i'm grouping the items & finding the % of times discount was applied to an item
from customer
group by item_purchased --out of total no of times the item was sold
order by discount_rate desc
limit 5;
/*so basically, if a Hat was sold 10 times 50% of the time,which means five times, the hat was sold 
with a discount.so this is helping us see which products rely heavily on discounts to sell*/
-------------------------------------------------------------------------------------------------------------


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment?
/*(IMP) bcz businesses love customer segmentation.It helps them understand customer loyality, so let's define how we can 
segment customers into new,returning & loyal. we'll segment it according to simple rule- let's say someone has 
bought only once from a store, then they're new but if previous purchases bet 2 & 10 times, then they are returning customers
& if they have purchased more than 10 times, then they're loyal customers. then we just have to count how many customers fall
into each bracket*/
with customer_type as (         -- CTE
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS Customer_segment
from customer
)

select customer_segment, COUNT(*) as "Number of customers"
from customer_type
group by customer_segment;  
/*so now we have 3116 loyal customers & new,returning customers are very less, bcz data we have is customer base, so there
are a lot of loyal customers in this dataset*/
-------------------------------------------------------------------------------------------------------------


--Q8. What are the top 3 most purchased products within each category?
/*this is advanced query we'll need a Window function(row) to rank products by total orders within category.Then we will
pick the top 3 & I also need a CTE for this query as well*/
with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(Partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
/*now we can see top 3 items within each category which r the best selling, now why we used ROW NUMBER instead of 
Dense rank & Rank, bcz you can see for many items the no.s are same.so, what rank 7 dense rank will do is they'll 
put sunglasses and belt both as Rank two, similarly rank & dense rank will put blouse & pants both as rank one.
But since we need three different ranks I took ROW NUMBER */
-------------------------------------------------------------------------------------------------------------


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
/*IMP Q, bcz if repeat buyers are also subscribers that's great for the business.But if loyal customers aren't subscribing
it may signal that the subscription offer isn't attractive enough for the customers.*/
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;
-- O/P- now we know that 2518 of repeat buyers are not subscribe but only 958 repeat buyers are subscribed to our model


-------------------------------------------------------------------------------------------------------------
--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
/* Op- so this is telling us which demographic is most valuable to the business, we can see young adults drive the most 
revenue & then it's followed by middle-aged, adult & senior citizens*/

--okay now that we have done our analysis in sql.. let's create a beautiful Dashboard in PowerBI